### ISSUE TITLE
Unused Variables Not Dimmed in Natty Theme for Visual Identification

### ISSUE THREAD

**Issue by nayon117** [this-fifo/natty-theme#1]
’m using the Natty theme in VS Code and noticed that unused variables are not visually dimmed or marked in any way. This makes it difficult to quickly identify variables that are declared but not used, which is a common feature in many themes.

I have tried customizing the theme settings, but with no success.

**Comment by this-fifo** [comment]
hey @nayon117, thank you for reporting this and I totally agree with you! — I will look into this once I have some bandwidth, if you find where this is controlled before I do please feel encouraged to add to this issue, suggest the changes, and make a PR. Contributions are much welcomed 🙏

**Comment by this-fifo** [comment]
hey @nayon117 — I just fixed this and published a new version! Thanks again for reporting, sorry for the delay, glad you enjoy the theme. :)

**Comment by nayon117** [comment]
Hey, thank you so much for the update! I really appreciate you taking the
time to fix it, and I have to say, this theme is truly underrated. It’s a
fantastic design that feels both professional and comfortable for extended
coding sessions—glad I discovered it! Thanks again for your hard work and
for making the VS Code experience even better. 😊
